version: "2.2"

services:
  mysql:
    image: mysql:8.0.28
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - "./src/main/resources/sql/schema.sql:/docker-entrypoint-initdb.d/1.sql"
      - "./src/main/resources/sql/data.sql:/docker-entrypoint-initdb.d/2.sql"